---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  OTBR_VERSION: latest
  UNIVERSAL_SILABS_FLASHER: 0.0.31
