---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  OTBR_VERSION: de0f77791eeb553c4c104a90958e04edb6f12206
  UNIVERSAL_SILABS_FLASHER: 0.0.31
